# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yHs7Wu6s31wpuUlp4VWoOiOKpHS4HZkM
"""

!pip install streamlit pyngrok

from pyngrok import ngrok
NGROK_AUTH_TOKEN = "35X1enl06ZPiM7fz9MqTVvg81t5_uDPpcW5GE1skBeJ2CS7o"
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

!pip install folium streamlit-folium

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from streamlit_folium import st_folium
# import folium
# 
# st.set_page_config(page_title="WLB Inspection App", layout="wide")
# 
# # Sidebar navigation
# page = st.sidebar.radio(
#     "Navigation",
#     ["Inspection Plan", "Map", "Alerts", "Tasks", "Section Completion"]
# )
# 
# # --------- Inspection Plan ----------
# if page == "Inspection Plan":
#     st.title("Inspection Plan")
#     st.subheader("Upcoming 5 km Inspection Sections")
#     st.info("Each section is inspected twice per year.")
# 
#     sections = [
#         ("10–15 km", "High Risk", "Vegetation + Deformation signals detected"),
#         ("15–20 km", "Medium Risk", "Vegetation trending upwards"),
#         ("20–25 km", "Low Risk", "Stable conditions")
#     ]
# 
#     for sec, risk, desc in sections:
#         st.markdown(f"### Section {sec}")
#         st.write(f"**Risk Level:** {risk}")
#         st.write(desc)
#         st.button(f"Open Map for {sec}")
# 
# # --------- Map (REAL MAP VERSION) ----------
# elif page == "Map":
#     st.title("Map View")
#     st.subheader("Satellite & Track Condition Map")
# 
#     # Create map centered near Vienna (dummy location)
#     m = folium.Map(location=[48.1, 16.3], zoom_start=11)
# 
#     # Realistic WLB corridor coordinates (Vienna → Baden)
#     corridor = [
#         [48.19834, 16.36958],  # Wien Oper
#         [48.18790, 16.35075],  # Wolfganggasse
#         [48.17540, 16.34310],  # Meidling
#         [48.16350, 16.33770],  # Inzersdorf
#         [48.14890, 16.32660],  # Vösendorf
#         [48.13490, 16.31420],  # Wiener Neudorf
#         [48.12220, 16.30440],  # Guntramsdorf
#         [48.10810, 16.29350],  # Pfaffstätten
#         [48.10300, 16.25800],  # Baden outskirts
#         [48.00241, 16.23196]   # Baden Josefsplatz
#     ]
# 
#     # Risk colors for each segment
#     segment_colors = ["green", "yellow", "red", "yellow", "green", "yellow", "red", "yellow", "green"]
# 
#     # Draw colored track segments
#     for i in range(len(corridor) - 1):
#         folium.PolyLine(
#             locations=[corridor[i], corridor[i+1]],
#             color=segment_colors[i],
#             weight=8,
#             tooltip=f"Segment {i+1}: {segment_colors[i].capitalize()} Risk"
#         ).add_to(m)
# 
#     # ------- ALERT MARKERS (placed ON the corridor) -------
# alert_points = [
#     (corridor[2], "Driver Report: Noise near track", "orange", "exclamation-sign"),
#     (corridor[4], "Vegetation Risk: Tree leaning towards catenary", "green", "leaf"),
#     (corridor[6], "Deformation: Possible ground movement", "red", "warning")
# ]
# 
# 
#     for loc, text, color, icon in alert_points:
#         folium.Marker(
#             location=loc,
#             popup=text,
#             icon=folium.Icon(color=color, icon=icon)
#         ).add_to(m)
# 
#     # Render map
#     st_data = st_folium(m, width=900, height=500)
# 
#     st.subheader("Selected Segment Details")
#     st.write("Click a marker or segment to inspect.")
#     st.write("Cause: Vegetation / Deformation / Driver Report")
#     st.write("Trend Chart (placeholder)")
#     st.button("Create Task")
# 
# # --------- Alerts ----------
# elif page == "Alerts":
#     st.title("Alerts")
#     st.error("Vegetation HIGH at km 12.4")
#     st.warning("Deformation MEDIUM at km 9.1")
#     st.info("Driver Report at km 4.0")
# 
# # --------- Tasks (Auto-generated from Alerts) ----------
# elif page == "Tasks":
#     st.title("Tasks")
#     st.subheader("Tasks Automatically Created from Alerts")
# 
#     # These mimic data coming from the Alerts tab
#     alerts = [
#         {"type": "Vegetation", "severity": "HIGH", "km": 12.4,
#          "description": "Tree canopy encroaching into catenary envelope"},
#         {"type": "Deformation", "severity": "MEDIUM", "km": 9.1,
#          "description": "Slight subsidence trend detected in last 3 Sentinel cycles"},
#         {"type": "Driver Report", "severity": "INFO", "km": 4.0,
#          "description": "Unusual noise reported during morning service"}
#     ]
# 
#     # Convert alerts → tasks
#     def alert_to_task(alert):
#         if alert["type"] == "Vegetation":
#             action = "Inspect vegetation near catenary"
#         elif alert["type"] == "Deformation":
#             action = "Check track geometry & mast stability"
#         elif alert["type"] == "Driver Report":
#             action = "Verify driver-reported anomaly"
#         else:
#             action = "General inspection"
#         return f"{action} @ km {alert['km']}"
# 
#     tasks = [alert_to_task(a) for a in alerts]
# 
#     # Display each task
#     for i, t in enumerate(tasks):
#         with st.container():
#             st.markdown(f"### {t}")
#             st.write(f"**Source Alert:** {alerts[i]['type']} — {alerts[i]['severity']}")
#             st.write(alerts[i]["description"])
# 
#             st.selectbox(
#                 "Outcome:",
#                 ["No Findings", "Risk Identified", "Needs Review"],
#                 key=f"outcome_{i}"
#             )
#             st.button("Mark Done", key=f"done_{i}")
# 
# # --------- Section Completion ----------
# elif page == "Section Completion":
#     st.title("Section Completion")
#     st.success("Auto-generated report: Photos: 3, Notes: 4, Issues: 2")
#     st.radio("Final Status:", ["Clear", "Issues Found"])
#

public_url = ngrok.connect(8501)
public_url

!streamlit run app.py